<?php


namespace bobroid\memesRedirectorBot\commands;


use bobroid\memesRedirectorBot\models\Configuration;
use Longman\TelegramBot\Entities\ServerResponse;
use Longman\TelegramBot\Exception\TelegramException;
use Longman\TelegramBot\Request;

/**
 * Trait CheckAccessTrait
 * @package bobroid\memesRedirectorBot\commands
 */
trait CheckAccessTrait
{

    /**
     * @return int|null
     */
    public function getChatId(): ?int
    {
        $chatId = null;

        if ($update = $this->getUpdate()) {
            if ($editedMessage = $update->getEditedMessage()) {
                $chatId = $editedMessage->getChat()->getId();
            } else if ($callbackQuery = $update->getCallbackQuery()) {
                $chatId = $callbackQuery->getMessage()->getChat()->getId();
            }
        } else if ($message = $this->getMessage()) {
            $message->getChat()->getId();
        }

        return $chatId;
    }

    /**
     * @return ServerResponse
     * @throws TelegramException
     */
    public function preExecute(): ServerResponse
    {
        $chatId = $this->getChatId();

        if (in_array($chatId, Configuration::getAdminsIDs(), true) === false) {
            return Request::sendMessage([
                'chat_id'   =>  $chatId,
                'text'      =>  'I work just from my creator, so sorry'
            ]);
        }

        return parent::preExecute(); // TODO: Change the autogenerated stub
    }

}