<?php


namespace bobroid\memesRedirectorBot\commands;


use bobroid\memesRedirectorBot\models\Configuration;
use Longman\TelegramBot\Entities\ServerResponse;
use Longman\TelegramBot\Exception\TelegramException;
use Longman\TelegramBot\Request;

/**
 * Trait CheckAccessTrait
 * @package bobroid\memesRedirectorBot\commands
 */
trait CheckAccessTrait
{

    /**
     * @return int|null
     */
    public function getChatId(): ?int
    {
        $chatId = null;

        if ($this->getUpdate() && $this->getUpdate()->getEditedMessage()) {
            $chatId = $this->getUpdate()->getEditedMessage()->getChat()->getId();
        } else if ($message = $this->getMessage()) {
            $message->getChat()->getId();
        }

        return $chatId;
    }

    /**
     * @return ServerResponse
     * @throws TelegramException
     */
    public function preExecute(): ServerResponse
    {
        \Yii::debug($this->getUpdate());
        \Yii::debug($this->getUpdate()->getCallbackQuery());
        \Yii::debug((($this->getUpdate() && $this->getUpdate()->getCallbackQuery()) === false));


        if (($this->getUpdate() && $this->getUpdate()->getCallbackQuery()) === false) {
            $chatId = $this->getChatId();

            if (in_array($chatId, Configuration::getAdminsIDs(), true) === false) {
                return Request::sendMessage([
                    'chat_id'   =>  $chatId,
                    'text'      =>  'I work just from my creator, so sorry'
                ]);
            }
        }

        return parent::preExecute(); // TODO: Change the autogenerated stub
    }

}