<?php


namespace bobroid\memesRedirectorBot;


use yii\i18n\PhpMessageSource;

class Module extends \yii\base\Module
{

    public $controllerNamespace = 'bobroid\memesRedirectorBot\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->registerTranslations();
    }


    private function registerTranslations(): void
    {
        \Yii::$app->i18n->translations['tg-posts-redirector'] = [
            'class'             =>  PhpMessageSource::class,
            'sourceLanguage'    =>  'ru-RU',
            'basePath'          =>  '@vendor/bobroid/yii2-memes-redirector-bot/messages',
        ];
    }
}